app = "crop-classifier-backend"
primary_region = "sjc"

[http_service]
  internal_port = 5003
  force_https = true

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "pip install -r requirements.txt"

[env]
  PORT = "5003"